### PR TITLE
YouTube video player lookalike

### PR DESCRIPTION
**Pull request by lmaldonadoch**
This is the first project of the HTML & CSS course. It is a copy of the YouTube website layout. We used www.fontawesome.com for some of the icons and SVG files for the other ones. We copied the images from an actual YouTube page and we used the modern version of the website.

### CODE REVIEW

**Comment by sumancrest0001** [comment]
[REQUIRED] Great job guys. The HTML file is clean and all the requirements are fulfilled. CSS naming convention is great. But there is a small change required. Please resize the width and height of the embedded video and the left margin of content__video div. 
[OPTIONAL] It will look good if you give some padding or margin to like, dislike and share buttons. It won't take long.
You guys are inch close to approval. Best of luck for the next submission.

**Comment by lmaldonadoch** [comment]
The issues have been resolved and we are awaiting comments.

**Comment by mikenath223** [comment]
### Pull Request currently under review by MIchgolden Ukeje (TSE)
Kindly exercise patience 🐱

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi @lmaldonadoch  and @shubhsk88 👋👋

I must commend the cleanliness of your codebase. **Well done on that 👏👏**

However, there are some important changes that need to be made before we can proceed:
**Kindly note that all sections marked as required are necessary to proceed**.

- [x] Required - The video element in the page covers almost all sections of the page, obstructing other elements. Kindly adjust its dimensions. Screenshot 👇
youtube1

- [x] - Required -  As seen in the original webpage there is a footer section on the page. Kindly add a footer section to your page with relevant nav links. Screenshot 👇
youtube2

- [x] - Required -  The original webpage also contains more videos in the aside section to the right, than yours. Kindly add this number of videos.

- [x] - Required - Add more margin both to the top and both sides of the top navbar element. 

- [x] - Required - Add a live version link to the readMe docs. You can consider using [githack](https://raw.githack.com/) to create a link. Simply paste your GitHub repo link there.

- [x] - Required - Remove all comments in your code. It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

- [ ] - Optional - Directly beneath the video section there is a loading gif. You can consider adding this. Screenshot 👇
ice_screenshot_20200325-004318

Kindly fix all changes and request another code review.

**Am rooting for you 💪**

Free free to reach out to me on slack via the handle @michgolden if you want further clarification.

HAPPY CODING TEAM 👨‍💻

**Comment by lmaldonadoch** [comment]
Thank you for the comments, We have completed the requirements and added responsiveness to the video to fit any screen. Cheers!

**Review by men32z — APPROVED** [review]
@lmaldonadoch, @shubhsk88 
Good job making the changes guys, you can merge.

**Pull request merged**
